cursor #c5c4dd
cursor_text_color #131318

foreground            #e4e1e9
background            #131318
selection_foreground  #2e2f42
selection_background  #c5c4dd
url_color             #bec2ff

# black
color8   #91909a
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green (优化为更舒适清晰的鼠尾草灰绿)
color2   #9ab38d
color10  #b0c9a3

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #bec2ff
color12 #a39ec4

# magenta
color5   #e7b9d5
color13  #ffd8ee

# cyan (绑定次要色，利用 fixed_dim 原生实现“调暗”效果，杜绝渲染报错)
color6   #c5c4dd
color14  #c5c4dd

# white
color15  #e7e7e7
color7   #f0f0f0
