cursor #dfe3e6
cursor_text_color #c0c8cd

foreground            #dfe3e6
background            #0f1417
selection_foreground  #1e333c
selection_background  #b4cad5
url_color             #8ad0ef

color0   #0f1417
color1   #e64c4b
color2   #74d66e
color3   #dbce7b
color4   #418eb0
color5   #76a0b3
color6   #8ad0ef
color7   #abb2bf
color8   #5c6370
color9   #e05f63
color10  #8be086
color11  #e8dd97
color12  #93dfff
color13  #39848f
color14  #587d9a
color15  #ffffff
