# ==============================
# Variables
# ==============================

$terminal = kitty
$browser = firefox
$fileManager = dolphin
$menu = rofi -show drun
$scriptsDir = ~/.config/hypr/scripts
$wallpaperScript = $scriptsDir/walls.sh
$screenshotScript = $scriptsDir/screenshot.sh
