# ==============================
# Autostart applications
# ==============================

# Only one polkit agent (remove the other)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = $terminal
exec-once = waybar
exec-once = swaync
#exec-once = $wallpaperScript
#exec-once = hyprctl setcursor Bibata-Modern-Ice 24
