# ==============================
# Window rules (floating, size, etc.)
# ==============================

windowrule = float, ^(pavucontrol)$
windowrule = float, ^(org.gnome.Calculator)$
windowrule = float, ^(org.kde.dolphin)$
windowrule = float, ^(Spotify)$
windowrule = size 800 600, ^(Spotify)$
windowrule = float, ^(Mission Center)$
windowrule = float, ^(AyuGram)$
# Add more as needed
