cursor #c0c6dd
cursor_text_color #121318

foreground            #e3e2e9
background            #121318
selection_foreground  #2a3042
selection_background  #c0c6dd
url_color             #b2c5ff

# black
color8   #8f909a
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green (优化为更舒适清晰的鼠尾草灰绿)
color2   #9ab38d
color10  #b0c9a3

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #b2c5ff
color12 #a39ec4

# magenta
color5   #e1bbdc
color13  #fed6f9

# cyan (绑定次要色，利用 fixed_dim 原生实现“调暗”效果，杜绝渲染报错)
color6   #c0c6dd
color14  #c0c6dd

# white
color15  #e7e7e7
color7   #f0f0f0
